### ISSUE TITLE
Sqlite Null Reference Exception

### ISSUE THREAD

**Issue by NPadrutt** [Apply-Solutions/MoneyManager#394]
System.NullReferenceExceptionArg_NullReferenceException

```c# 
 at SQLite.Net.TableQuery<System.Object>.CompileExpr(Linq.Expressions.Expression expr, Collections.Generic.List<System.Object> queryArgs)
   at SQLite.Net.TableQuery<System.Object>.CompileExpr(Linq.Expressions.Expression expr, Collections.Generic.List<System.Object> queryArgs)
   at SQLite.Net.TableQuery<System.Object>.CompileExpr(Linq.Expressions.Expression expr, Collections.Generic.List<System.Object> queryArgs)
   at SQLite.Net.TableQuery<System.Object>.CompileExpr(Linq.Expressions.Expression expr, Collections.Generic.List<System.Object> queryArgs)
   at SQLite.Net.TableQuery<System.Object>.CompileExpr(Linq.Expressions.Expression expr, Collections.Generic.List<System.Object> queryArgs)
   at SQLite.Net.TableQuery<System.Object>.GenerateCommand(String selectionList)
   at SQLite.Net.TableQuery<System.Object>.GetEnumerator()
   at System.Collections.Generic.List<System.Action>..ctor(Collections.Generic.IEnumerable<System.Action> collection)
   at MoneyManager.Windows!<BaseAddress>+0xb66e8e
   at MoneyManager.Core.DataAccess.TransactionDataAccess.GetListFromDb(Linq.Expressions.Expression<System.Func<MoneyManager.Foundation.Model.FinancialTransaction,System.Boolean>> filter)
   at MoneyManager.Foundation.AbstractDataAccess<System.Object>.LoadList(Linq.Expressions.Expression<System.Func<System.Object,System.Boolean>> filter)

```

**Comment by NPadrutt** [comment]
Should be fixed I guess.
